# Generated by Django 2.0.5 on 2018-06-06 19:27

import datetime
from django.conf import settings
from django.db import migrations, models
import historymap.users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.URLField()),
                ('times_hovered_over', models.BigIntegerField(default=0)),
                ('times_clicked_on', models.BigIntegerField(default=0)),
                ('times_searched', models.BigIntegerField(default=0)),
                ('wikipedia_title_url', models.TextField(default='')),
                ('last_visited', models.DateTimeField(default=datetime.datetime.now)),
                ('first_visited', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=models.SET(historymap.users.models.get_new_deleted_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
