# Generated by Django 2.0.5 on 2018-06-09 18:09

import datetime
from django.conf import settings
from django.db import migrations, models
import historymap.users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_userarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('times_requested', models.BigIntegerField(default=0)),
                ('first_visited', models.DateTimeField(default=datetime.datetime.now)),
                ('last_visited', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=models.SET(historymap.users.models.get_new_deleted_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
